site_name: mlflow-assistant
site_description: Documentation for the mlflow-assistant CLI
site_url: https://hugodscarvalho.github.io/mlflow-assistant/
repo_url: https://github.com/hugodscarvalho/mlflow-assistant
repo_name: hugodscarvalho/mlflow-assistant
use_directory_urls: true

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "#FAFAFA"   # Off-White
      accent: "#BCAAA4"   # Warm Taupe
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "#333333"   # Dark Charcoal
      accent: "#D7CCC8"   # Light Taupe
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - content.tabs.link # Make tabbed content linkable
    - content.action.edit:
        url: https://github.com/hugodscarvalho/mlflow-assistant/edit/main/docs/{path}
        label: Edit this page
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Installation: installation.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            heading_level: 2
  - section-index

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hugodscarvalho/mlflow-assistant