name: Deploy Documentation to GitHub Pages

on: [push, pull_request]

permissions:
  contents: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for proper history and commit timestamps

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Or your desired Python version

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-interaction

      - name: Build Documentation
        run: |
          poetry run mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site # The directory where MkDocs builds the site